REPLACE INTO `spell_areatrigger` (`spell_id`, `selection`, `radius`, `ScriptName`, `Comment`) VALUES 
(13810, 2, 10, 'spell_area_hunter_ice_trap', 'Ice Trap, Hunter'),
(102793, 2, 8, 'spell_area_druid_ursols_vortex', 'Ursol\'s Vortex, Druid'),
(115460, 1, 1, 'spell_area_monk_healing_sphere', 'Healing Sphere, Monk'),
(115817, 1, 6, 'spell_area_fen_cancel_barrier', 'Cancel Barrier, Feng'),
(116011, 1, 5, 'spell_area_mage_rune_of_power', 'Rune of Power, Mage'),
(116235, 2, 3.5, 'spell_area_stone_guard_ametyst_pool', 'Ametyst Pool, Stone Guard'),
(116546, 2, 30, 'spell_area_elegon_draw_power', 'Draw Power, Elegon'),
(117032, 1, 1, 'spell_area_monk_healing_sphere_afterlife', 'Healing Sphere (afterlife), Monk'),
(119031, 1, 1, 'spell_area_monk_gift_of_the_serpent', 'Gift of the Serpent, Monk'),
(121286, 1, 1, 'spell_area_monk_chi_sphere_afterlife', 'Chi Sphere (afterlife), Monk'),
(121536, 1, 1, 'spell_area_priest_angelic_feather', 'Angelic Feather, Priest'),
(122035, 2, 1, 'spell_area_monk_path_of_blossom', 'Path of Blossom, Monk'),
(124503, 1, 1, 'spell_area_monk_gift_of_the_ox_1', 'Gift of the Ox, Monk'),
(124506, 1, 1, 'spell_area_monk_gift_of_the_ox_2', 'Gift of the Ox, Monk'),
(122731, 2, 3, 'spell_area_imperial_vizier_zorlok_noise_cancelling', 'Noise Cancelling, Imperial Vizier Zor\'lok'),
(123461, 2, 60, 'spell_area_lei_shi_get_away', 'Get Away, Lei Shi'),
(123811, 2, 35, 'spell_area_imperial_vizier_zorlok_pheromones_of_zeal', 'Pheromones of Zeal, Imperial Vizier Zor\'lok'),
(144692, 2, 15, 'spell_area_ordos_pool_of_fire', 'Pool of Fire, Ordos');
